### PR TITLE
#187 2.16 language issues

### PR DESCRIPTION
**Pull request by nilsthamm**
Closing #187

### CODE REVIEW

**Review by cmfcmf — APPROVED** [review]
LGTM

**Review by bjrne — DISMISSED** [review]
Are you sure that this only has a line diff of +2-1? The commits suggest something else... Feel free to dismiss my review if you are sure about this.

**Comment by cmfcmf** [comment]
> Are you sure that this only has a line diff of +2-1? The commits suggest something else...

https://github.com/hpi-swt2/workshop-portal/pull/229 and https://github.com/hpi-swt2/workshop-portal/pull/234 already fixed a bunch of language issues.

**Comment by bjrne** [comment]
Look at commit 2834230. I don't see its diff in the final one. Or do I miss something here?

**Comment by cmfcmf** [comment]
> Look at commit 2834230. I don't see its diff in the final one. Or do I miss something here?

As I said, this has already been included in one of the other pull requests 😃

**Pull request merged**
