### PR TITLE
25 4.1 letter of agreement

### PR DESCRIPTION
**Pull request by phnm**
US_4.1 (#25)
Implemented the ability to upload a letter of agreement for every event for which one has an accepted application to one's profile, if one is <18 years of age.

### CODE REVIEW

**Comment by cmfcmf** [comment]
Shouldn't this be merged into `dev`, not `master`?

**Review by bjrne — DISMISSED** [review]
Please don't create pull requests for features into master. Use dev instead. Moreover, take a good look on you tests, they don't seem to cover everything.

**Comment by Blaidd-Drwg** [comment]
PR #74 already adds [tests](https://github.com/hpi-swt2/workshop-portal/blob/6c9a7bb7b533b484b8d4f8c646a60cf9a953d90d/spec/models/event_spec.rb#L24) for that function. We could cherry-pick them into this branch if you think it's necessary.

**Comment by bjrne** [comment]
Neither of both PRs have 100% test coverage... Either add the tests to the corresponding PR or wait for the tests to be merged, so we always have 100% coverage.

**Comment by pinussilvestrus** [comment]
Code Review: Approve
Merge it after solve conflicts..

**Review by pinussilvestrus — APPROVED** [review]
good job.

**Pull request merged**
