### PR TITLE
Edited list views

### PR DESCRIPTION
**Pull request by nilsthamm**
ref #309

### CODE REVIEW

**Comment by cmfcmf** [comment]
@tom95 didn't you also work on these?

**Review by hefowe — COMMENTED** [review]
@nilsthamm Why do you use a css id for profile_details and a css class for request_details?

**Comment by nilsthamm** [comment]
@hefowe you are right, that makes no sense. I think it was a copy paste error, i will change the profile_details id into a class...

**Review by hefowe — APPROVED** [review]
Looks good

**Pull request merged**
