### PR TITLE
For when the page doesn't come out as speedy as the click came in.

### PR DESCRIPTION
**Pull request by tom95**
Adds a subtle loading animation in the bottom right.

### CODE REVIEW

**Comment by bjrne** [comment]
I like it. @hpi-swt2/scrum-master-2016 @hpi-swt2/product-owner-2016 ?

**Comment by Baschdl** [comment]
Looks good, but maybe a little bit annoying when you open many pages.

**Review by MasterCarl — APPROVED** [review]
Pretty cool, I like it

**Review by cmfcmf — APPROVED** [review]
Looks great! I fixed one last merge conflict so this can be merged :)

**Pull request merged**
