### PR TITLE
511 xss attack via custom markdown render truncate

### PR DESCRIPTION
**Pull request by hefowe**
Refs #511.

### CODE REVIEW

**Comment by hefowe** [comment]
@cmfcmf is this fix good enough? Is there still a way to bypass it?

**Comment by cmfcmf** [comment]
> @cmfcmf is this fix good enough? Is there still a way to bypass it?

I'm afraid this isn't the correct fix. You now strip all the HTML even if the `Redcarpet::Render::HTML` renderer is used. But we want that HTML.

**Comment by hefowe** [comment]
@cmfcmf you are right.  Which tags should be allowed? Or can we just strip the html from the index event page? I think we do not need the html on this page?

**Comment by cmfcmf** [comment]
> Or can we just strip the html from the index event page?

Well, this is what the `MarkdownRenderTruncate` was initially made for. I think it would be sufficient to call `CGI::escapeHTML(...)` on the `text` and `content` variables in here: https://github.com/hpi-swt2/workshop-portal/blob/d7e3194b7788c1c377a2ca7a8e81f527efeb5ec6/app/helpers/application_helper.rb#L6

**Comment by hefowe** [comment]
@cmfcmf Thanks for your help!

**Review by nilsthamm — APPROVED** [review]

**Pull request merged**
