### PR TITLE
46_1.7_Additional_Information bugfix and migrations fix

### PR DESCRIPTION
**Pull request by MasterCarl**
The application as merged in the previous pull request didn't save the new attributes

### CODE REVIEW

**Review by Baschdl — COMMENTED** [review]
Looks good to me. Nice feature!

**Review by bjrne — COMMENTED** [review]
Please await feedback for the issue with your migration in the main PR #71 for this and add changes to this PR if necessary.

**Comment by bjrne** [comment]
Reviewer: Please test this locally on your machine to be absolutely sure it works with the current version of you database!

**Comment by MasterCarl** [comment]
As I discussed with @bjrne, it would be nice if someone else could review this

**Comment by MasterCarl** [comment]
Since 49d3c4aa5e7461bb85109bfe6fbf2a1f7f1f073c, migrations would fail for users using the dev branch after 1cf5807c70f36857bf7df4edd7516f310569fb31. It should now work again for both cases.

**Review by tom95 — APPROVED** [review]
The unless column_exists fixes it perfectly, nice find!

**Comment by nilsthamm** [comment]
Next time please use squash and merge!

**Pull request merged**
