### PR TITLE
429_login_error_rework

### PR DESCRIPTION
**Pull request by hefowe**
Refs #429.

### CODE REVIEW

**Comment by bjrne** [comment]
It should work for now, but I don't really like it. It depends heavily on the correct translation of both strings into every language we might support since we still get two different strings from devise. Might there be another solution?

**Comment by hefowe** [comment]
@bjrne You are right, there should be a better way. Devise itself uses this solution: You can look at the translations https://github.com/tigrish/devise-i18n/tree/master/rails/locales. Devise uses the same string for 'invalid' and 'not_found_in_database' for many languages.

**Comment by bjrne** [comment]
@hefowe Weird. But do you know what the paranoid mode does then?

**Review by bjrne — APPROVED** [review]
Since devise itself uses this solution, this should be fine 🗝

**Pull request merged**
