### PR TITLE
20 2.4 profile information coaches can view others applications

### PR DESCRIPTION
**Pull request by aloeser**
From our understanding coaches/tutors should be able to view application letters of other users, which is prohibited by the current implementation.

### CODE REVIEW

**Comment by cmfcmf** [comment]
👎 I don't think this is what's wanted. At least I could never look into application letters of users for the past Schülerklub events.

**Comment by aloeser** [comment]
@cmfcmf have you checked #24?
It says:
**As**
organizer or coach

**I want to**
be able to take notes on applications which other coaches can see

For me, this means a coach has to be able to see all applications for an event, not just his own.

**Comment by tobiduer** [comment]
Alex is right. Coaches must be able to see applications, but not the personal information (addresse, ... ) 
They should vote for applications, therefore they should be able to read the letter of motivation.

**Comment by cmfcmf** [comment]
> Alex is right. Coaches must be able to see applications, but not the personal information (addresse, ... )
> They should vote for applications, therefore they should be able to read the letter of motivation.

Ah, I see! Thank you for clarifying, Tobi!

**Review by ekrebs5 — APPROVED** [review]

**Review by querenker — APPROVED** [review]

**Pull request merged**
